### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by Excelsior-WYH** [RedrockTeam/RedUI#1]
加油💪

**Comment by HellowVirgil** [comment]
这是用啥撸？Vue？

**Comment by ChauMing** [comment]
好紧张, 被大佬围观了.

**Comment by Lich2013** [comment]
JB工程师看着你们

**Comment by YiKeYaTu** [comment]
雅儿嘛 被围观好紧张

**Comment by wssgcg1213** [comment]
![image](https://cloud.githubusercontent.com/assets/3922719/19804871/ad81303c-9d43-11e6-9c63-ee74d56fea52.png)

**Comment by wssgcg1213** [comment]
你们 1.0.0 还没发吧？把第一个版本号改成 0.0.1，然后切一个 v0.0.1的分支，在上面做开发

**Comment by wssgcg1213** [comment]
你们好好看一下http://semver.org/lang/zh-CN/ 这个和https://docs.npmjs.com/misc/semver，
0.0.1-0.1.0
0.1.0-1.0.0
1.0.0-
这三个阶段 npm 对包的自动升级机制是不同的

**Comment by Excelsior-WYH** [comment]
Git Commit 可以定个规范

[Angular代码提交规范](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format)
- feat: 新功能
- fix: 修复问题
- docs: 修改文档
- style: 修改代码格式，不影响代码逻辑
- refactor: 重构代码，理论上不影响现有功能
- perf: 提升性能
- test: 增加修改测试用例
- chore: 修改工具相关（包括但不限于文档、代码生成等）
- deps: 升级依赖

**Comment by wssgcg1213** [comment]
迁移至 https://github.com/Red-UI  @All
